<a href="https://colab.research.google.com/github/buffolu/pytorch-tutorial-youtube-codemy.com-/blob/main/lesson3_tensor_math_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [4]:
#Addition
tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
#Subtraction
tensor_b - tensor_a


tensor([4, 4, 4, 4])

In [8]:
#sub function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [9]:
#multipication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
#mul longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#Devision
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#div LongHand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
#Reminder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [14]:
#Reminder Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [15]:
#Exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [16]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
#Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [18]:
#long hand
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a

tensor([ 6,  8, 10, 12])