<a href="https://colab.research.google.com/github/buffolu/pytorch-tutorial-youtube-codemy.com-/blob/main/tensor_operations_lesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#reshape nad View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
#reshape if we dont know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

my_torch3 = torch.arange(10)
my_torch3


In [10]:
my_torch4 =my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#diffrence beetwen view and shape:
https://www.geeksforgeeks.org/whats-the-difference-between-reshape-and-view-in-pytorch/


In [11]:
my_torch7 =  torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#grab a specific item
my_torch[7]

tensor(7)

In [13]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [14]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [15]:
#return a column
my_torch8[:,1:]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])